apiVersion: v1
kind: Service
metadata:
  name: {{ include "throttler.name" . }}-app
  labels:
    {{- include "throttler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "throttler.selectorLabels" . | nindent 4 }}
  ports:
    {{- range $name, $port := .Values.service.ports }}
    - name: {{ $name }}
      port: {{ $port.port }}
      targetPort: {{ $port.targetPort }}
      protocol: {{ $port.protocol }}
    {{- end }}
